Fix: leaderboard dark mode color scheme
MLH-Fellowship/pod-4.1.4-portfolio pull request #36
Opened 2021-11-15 01:35 UTC by obasekiosa

This PR sets a higher colour scheme for the leaderboard.
This improves the readability of the leaderboard text.

---before---
![image](https://user-images.githubusercontent.com/12957252/141708775-4af3537e-62df-44d9-bb33-ac3c873fcfe0.png)

---after----
![image](https://user-images.githubusercontent.com/12957252/141708809-6196bde3-2fd3-49c9-9595-63f10a6e0e90.png)

fixes #32 

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

2021-11-16 22:29 UTC, NoahCardoza requested changes
1. I would also suggest darkening the shadow (I tried `#000000` and it looks pretty good).
2. I'd also darken the border on the `td` elements to create a more cohesive look. (I tried `#565656`).
3. Finally, I'd think about removing the `border-top` for the header. It looks fine in light mode, but it sticks out in dark mode.

Overall great work! Don't forget to ask for help from your pod mates or me!

2021-11-16 22:29 UTC, NoahCardoza commented on _sass/leaderboard.scss
> +  tr:nth-child(2n + 1) {
Here we can just set the color for all `tr`'s:

```suggestion
  tr {
```

2021-11-16 22:29 UTC, NoahCardoza commented on _sass/leaderboard.scss
> +    color: white;
And then we can remove this line since it's covered in our base case for all `tr`'s

```suggestion
```

2021-11-16 22:29 UTC, NoahCardoza commented on _sass/leaderboard.scss
> +    background-color: grey;
While it's easy to use the named colors (e.g. red, blue, grey ...) they are often a little too general to fit nicely. I'd recommend something like: 

```suggestion
    background-color: #23252B;
```

2021-11-26 16:08 UTC, obasekiosa commented
@NoahCardoza 
All done with the updates here

2021-12-01 18:26 UTC, NoahCardoza commented
LGTM!

2021-12-01 18:26 UTC, merged